import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <nav className='flex justify-between gap-4 bg-gray-400 text-white p-4 radius-lg'>  
        <div>
          <button>Options</button>
        </div>
        <div>
          <h1>Copa Simulator</h1>
        </div>
        <div className='flex gap-4'>
          <button>Login</button>
          <button>Register</button>
        </div>
      </nav>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
